services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Dev\FileBundle\:
        resource: '../../*'
        exclude: "../../{DependencyInjection,Resources,ExceptionInterface,NamingStrategy,Model,Mapping,Entity,Events}"

    Dev\FileBundle\Handler\Handler:
        lazy: true

    Dev\FileBundle\Storage\FileSystemStorage:
        arguments: [ "%dev_file.storage.path%", "%dev_file.storage.uri_prefix%" ]

    Dev\FileBundle\Mapping\Driver\UploadableDriver:
        autowire: true
        autoconfigure: true